title: Ioniq 5 Diagnostics
description: iOS diagnostics app for the Hyundai Ioniq 5
remote_theme: just-the-docs/just-the-docs

baseurl: "/ioniq-app"
url: "https://www.theburl.com"

color_scheme: dark

search_enabled: true

aux_links:
  "Report an Issue":
    - "https://github.com/gburlingame/ioniq-app/issues"
