title: IONIQ 5 Companion
description: iOS diagnostics app for the Hyundai IONIQ family
remote_theme: just-the-docs/just-the-docs

baseurl: "/ioniq-app"
url: "https://www.theburl.com"

color_scheme: ioniq

search_enabled: true

aux_links:
  "Report an Issue":
    - "https://github.com/gburlingame/ioniq-app/issues"
